-- Add additional supplier columns
ALTER TABLE suppliers
  ADD COLUMN IF NOT EXISTS website VARCHAR(255),
  ADD COLUMN IF NOT EXISTS executive_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS phone1 VARCHAR(32),
  ADD COLUMN IF NOT EXISTS phone2 VARCHAR(32),
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS city VARCHAR(128),
  ADD COLUMN IF NOT EXISTS tin_gstin VARCHAR(64),
  ADD COLUMN IF NOT EXISTS state VARCHAR(128);
