name: Check migrations

on:
  pull_request:

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: backend
        run: npm ci
      - name: Run migration scanner
        working-directory: backend
        run: node ./scripts/check-migrations.js
