name: e2e-tests

on:
  push:
    branches: [ main, fix/* ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: billing_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Run migrations
        working-directory: backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/billing_test
        run: npm run migrate

      - name: Run backend integration tests
        working-directory: backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/billing_test
        run: |
          # Run jest integration tests serially to avoid DB conflicts
          npm test -- --runInBand --color
