name: spin
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
      response_url:
        type: string
        required: true

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ---------- FRONTEND ----------
      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Publish to Cloudflare Pages
        id: pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: billinApp     # <-- set your Pages project name
          directory: frontend/dist            # Vite output (change if CRA)
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Capture FE URL
        run: echo "FE_URL=${{ steps.pages.outputs.url }}" >> $GITHUB_ENV

      # ---------- BACKEND (stub; replace with your real deploy) ----------
      - name: Deploy backend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
          # TODO: set BE_URL properly; using a placeholder here
          echo "BE_URL=https://$RENDER_SERVICE_ID.onrender.com" >> $GITHUB_ENV

      # ---------- SLACK NOTIFY ----------
      - name: Notify Slack
        run: |
          curl -X POST -H "Content-type: application/json" "${{ inputs.response_url }}" \
            -d "{\"text\":\"✅ *${{ inputs.branch }}* deployed!\\nFrontend: ${{ env.FE_URL }}\\nBackend: ${{ env.BE_URL }}\"}"
